// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qejganytvxciefrppvot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlamdhbnl0dnhjaWVmcnBwdm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzYwMjMsImV4cCI6MjA2NjM1MjAyM30.uvb8Rd0DjzpW9Nw-d7uc153AGO3_8bRV4hnW6w3o0Cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);